In [2]:
import sys
print(sys.executable)

d:\task1\venv\Scripts\python.exe

In [3]:
import numpy as np
print(np.__version__)

1.26.4

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
import os
print(os.getcwd())

d:\task1\notebook

In [6]:
df = pd.read_csv(r"D:\task1\dataset\housing_data.csv")

In [7]:
df.head()

,country,iso,year,house_price_index,personal_disposable_income,real_house_price_index,real_personal_disposable_income,affordability_proxy
0,Australia,AUS,1975,2.83,7.19,21.89,55.72,39.29
1,Australia,AUS,1976,3.19,8.11,21.65,55.04,39.34
2,Australia,AUS,1977,3.48,8.91,21.43,54.88,39.05
3,Australia,AUS,1978,3.75,9.85,21.28,55.91,38.06
4,Australia,AUS,1979,4.20,10.80,21.75,55.94,38.88

In [8]:
df.shape

(1326, 8)

In [9]:
df.columns

Index(['country', 'iso', 'year', 'house_price_index',
       'personal_disposable_income', 'real_house_price_index',
       'real_personal_disposable_income', 'affordability_proxy'],
      dtype='object')

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1326 entries, 0 to 1325
Data columns (total 8 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   country                          1326 non-null   object
 1   iso                              1326 non-null   object
 2   year                             1326 non-null   int64
 3   house_price_index                1326 non-null   float64
 4   personal_disposable_income       1326 non-null   float64
 5   real_house_price_index           1326 non-null   float64
 6   real_personal_disposable_income  1326 non-null   float64
 7   affordability_proxy              1326 non-null   float64
dtypes: float64(5), int64(1), object(2)
memory usage: 83.0+ KB

In [11]:
df.isnull().sum()

country                            0
iso                                0
year                               0
house_price_index                  0
personal_disposable_income         0
real_house_price_index             0
real_personal_disposable_income    0
affordability_proxy                0
dtype: int64

In [12]:
df.duplicated().sum()

0

In [13]:
df.dtypes

country                             object
iso                                 object
year                                 int64
house_price_index                  float64
personal_disposable_income         float64
real_house_price_index             float64
real_personal_disposable_income    float64
affordability_proxy                float64
dtype: object

In [14]:
df["year"] = df["year"].astype(int)

In [15]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(" ", "_")

In [ ]:
plt.figure(figsize=(12,6))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.show()

In [ ]:
plt.figure(figsize=(10,5))
sns.boxplot(data=df.select_dtypes(include=np.number))
plt.xticks(rotation=90)
plt.show()

In [18]:
Q1 = df.select_dtypes(include=np.number).quantile(0.25)
Q3 = df.select_dtypes(include=np.number).quantile(0.75)

IQR = Q3 - Q1

df = df[~((df.select_dtypes(include=np.number) < (Q1 - 1.5 * IQR)) |
          (df.select_dtypes(include=np.number) > (Q3 + 1.5 * IQR))).any(axis=1)]

In [19]:
from sklearn.preprocessing import LabelEncoder

le_country = LabelEncoder()
df["country_encoded"] = le_country.fit_transform(df["country"])

le_iso = LabelEncoder()
df["iso_encoded"] = le_iso.fit_transform(df["iso"])

df.head()

,country,iso,year,house_price_index,personal_disposable_income,real_house_price_index,real_personal_disposable_income,affordability_proxy,country_encoded,iso_encoded
0,Australia,AUS,1975,2.83,7.19,21.89,55.72,39.29,0,0
1,Australia,AUS,1976,3.19,8.11,21.65,55.04,39.34,0,0
2,Australia,AUS,1977,3.48,8.91,21.43,54.88,39.05,0,0
3,Australia,AUS,1978,3.75,9.85,21.28,55.91,38.06,0,0
4,Australia,AUS,1979,4.20,10.80,21.75,55.94,38.88,0,0

In [20]:
df.to_csv(r"D:\task1\dataset\cleaned_housing_data.csv", index=False)

In [21]:
df.head()

,country,iso,year,house_price_index,personal_disposable_income,real_house_price_index,real_personal_disposable_income,affordability_proxy,country_encoded,iso_encoded
0,Australia,AUS,1975,2.83,7.19,21.89,55.72,39.29,0,0
1,Australia,AUS,1976,3.19,8.11,21.65,55.04,39.34,0,0
2,Australia,AUS,1977,3.48,8.91,21.43,54.88,39.05,0,0
3,Australia,AUS,1978,3.75,9.85,21.28,55.91,38.06,0,0
4,Australia,AUS,1979,4.20,10.80,21.75,55.94,38.88,0,0

In [22]:
df.tail()
df

,country,iso,year,house_price_index,personal_disposable_income,real_house_price_index,real_personal_disposable_income,affordability_proxy,country_encoded,iso_encoded
0,Australia,AUS,1975,2.83,7.19,21.89,55.72,39.29,0,0
1,Australia,AUS,1976,3.19,8.11,21.65,55.04,39.34,0,0
2,Australia,AUS,1977,3.48,8.91,21.43,54.88,39.05,0,0
3,Australia,AUS,1978,3.75,9.85,21.28,55.91,38.06,0,0
4,Australia,AUS,1979,4.20,10.80,21.75,55.94,38.88,0,0
...,...,...,...,...,...,...,...,...,...,...
1321,Portugal,PRT,2021,67.52,80.26,78.01,92.78,84.08,17,21
1322,Portugal,PRT,2022,79.70,86.04,85.81,92.77,92.50,17,21
1323,Portugal,PRT,2023,90.76,93.28,93.25,95.83,97.31,17,21
1324,Portugal,PRT,2024,100.00,100.00,100.00,100.00,100.00,17,21
1325,Portugal,PRT,2025,118.82,101.97,115.88,99.62,116.32,17,21